(deftheme warp-dark "Warp Dark Theme - A dark theme inspired by Warp.dev")

(let*
  (
    (bg "#000000")
    (bg-light "#0a0a0a")
    (bg-lighter "#111111")
    (fg "#ffffff")
    (fg-dim "#808080")
    (fg-darker "#4a4a4a")
    (border "#1a1a1a")
    (accent "#00c2ff")
    (accent-secondary "#b4fa72")
    (accent-tertiary "#ff8ffd")

    (syntax-comment "#616161")
    (syntax-keyword "#00c2ff")
    (syntax-keyword-operator "#a5d5fe")
    (syntax-string "#b4fa72")
    (syntax-number "#fefdc2")
    (syntax-constant "#fefdc2")
    (syntax-function "#d0d1fe")
    (syntax-variable "#ffffff")
    (syntax-parameter "#ffc4bd")
    (syntax-type "#fefdc2")
    (syntax-property "#c1e3fe")
    (syntax-tag "#ff8272")
    (syntax-attribute "#ff8ffd")
    (syntax-punctuation "#8e8e8e")

    (term-black "#616161")
    (term-red "#ff8272")
    (term-green "#b4fa72")
    (term-yellow "#fefdc2")
    (term-blue "#a5d5fe")
    (term-magenta "#ff8ffd")
    (term-cyan "#d0d1fe")
    (term-white "#f1f1f1")
  )

  (custom-theme-set-faces
    'warp-dark

    `(default ((t (:background ,bg :foreground ,fg))))
    `(fringe ((t (:background ,bg :foreground ,fg-dim))))
    `(minibuffer-prompt ((t (:foreground ,accent))))
    `(header-line ((t (:background ,bg :foreground ,fg-dim))))

    `(cursor ((t (:background ,accent :foreground ,bg))))
    `(highlight ((t (:background "#00c2ff2a"))))
    `(region ((t (:background "#00c2ff2a"))))
    `(secondary-selection ((t (:background "#00c2ff1a"))))
    `(isearch ((t (:background ,accent-tertiary :foreground ,bg))))
    `(isearch-fail ((t (:foreground ,term-red))))
    `(lazy-highlight ((t (:background "#00c2ff1a"))))

    `(font-lock-comment-face ((t (:foreground ,syntax-comment :italic t))))
    `(font-lock-comment-delimiter-face ((t (:foreground ,syntax-comment :italic t))))
    `(font-lock-keyword-face ((t (:foreground ,syntax-keyword))))
    `(font-lock-keyword-face ((t (:foreground ,syntax-keyword))))
    `(font-lock-operator-face ((t (:foreground ,syntax-keyword-operator))))
    `(font-lock-string-face ((t (:foreground ,syntax-string))))
    `(font-lock-number-face ((t (:foreground ,syntax-number))))
    `(font-lock-constant-face ((t (:foreground ,syntax-constant))))
    `(font-lock-function-name-face ((t (:foreground ,syntax-function))))
    `(font-lock-variable-name-face ((t (:foreground ,syntax-variable))))
    `(font-lock-type-face ((t (:foreground ,syntax-type))))
    `(font-lock-property-name-face ((t (:foreground ,syntax-property))))
    `(font-lock-tag-face ((t (:foreground ,syntax-tag))))
    `(font-lock-attribute-name-face ((t (:foreground ,syntax-attribute :italic t))))
    `(font-lock-punctuation-face ((t (:foreground ,syntax-punctuation))))
    `(font-lock-preprocessor-face ((t (:foreground ,syntax-keyword))))

    `(mode-line ((t (:background ,bg-light :foreground ,fg-dim :box ,border))))
    `(mode-line-inactive ((t (:background ,bg-light :foreground ,fg-darker :box ,border))))
    `(mode-line-buffer-id ((t (:foreground ,accent))))
    `(mode-line-emphasis ((t (:foreground ,fg))))
    `(mode-line-highlight ((t (:foreground ,accent))))

    `(vertical-border ((t (:foreground ,border))))
    `(window-divider ((t (:foreground ,border))))
    `(window-divider-first-pixel ((t (:foreground ,border))))
    `(window-divider-last-pixel ((t (:foreground ,border))))

    `(scroll-bar ((t (:background ,bg :foreground ,border))))
    `(tool-bar ((t (:background ,bg-light :foreground ,fg-dim))))
    `(tooltip ((t (:background ,bg-lighter :foreground ,fg))))

    `(completions-highlight ((t (:background "#00c2ff2a"))))

    `(company-tooltip ((t (:background ,bg-lighter :foreground ,fg))))
    `(company-tooltip-selection ((t (:background "#00c2ff1a" :foreground ,fg))))
    `(company-tooltip-mouse ((t (:background "#00c2ff2a"))))
    `(company-tooltip-common ((t (:foreground ,accent))))
    `(company-preview ((t (:background ,bg-lighter))))
    `(company-preview-search ((t (:background ,accent :foreground ,bg))))

    `(counsel-key-binding ((t (:foreground ,accent))))

    `(dired-directory ((t (:foreground ,syntax-function))))
    `(dired-flagged ((t (:foreground ,term-red))))
    `(dired-header ((t (:foreground ,accent))))
    `(dired-ignored ((t (:foreground ,fg-darker))))
    `(dired-mark ((t (:foreground ,accent))))
    `(dired-marked ((t (:foreground ,accent-tertiary))))
    `(dired-perm-write ((t (:foreground ,term-red))))
    `(dired-symlink ((t (:foreground ,syntax-keyword))))
    `(dired-warning ((t (:foreground ,term-yellow))))

    `(eldoc-highlight-function-argument ((t (:background "#00c2ff2a" :foreground ,fg))))

    `(error ((t (:foreground ,term-red))))
    `(warning ((t (:foreground ,term-yellow))))
    `(success ((t (:foreground ,term-green))))
    `(info ((t (:foreground ,accent))))

    `(diff-added ((t (:foreground ,term-green))))
    `(diff-changed ((t (:foreground ,term-yellow))))
    `(diff-removed ((t (:foreground ,term-red))))
    `(diff-header ((t (:foreground ,fg-dim))))
    `(diff-file-header ((t (:foreground ,accent))))
    `(diff-hunk-header ((t (:foreground ,fg-dim :background ,bg-lighter))))

    `(magit-section-heading ((t (:foreground ,accent))))
    `(magit-section-highlight ((t (:background ,bg-lighter))))
    `(magit-diff-added ((t (:foreground ,term-green :background "#00c2ff2a"))))
    `(magit-diff-added-highlight ((t (:foreground ,term-green :background "#00c2ff3a"))))
    `(magit-diff-removed ((t (:foreground ,term-red :background "#ff82722a"))))
    `(magit-diff-removed-highlight ((t (:foreground ,term-red :background "#ff82723a"))))
    `(magit-diff-context ((t (:foreground ,fg-dim))))
    `(magit-diff-hunk-header ((t (:foreground ,fg-dim :background ,bg-lighter))))
    `(magit-blame-heading ((t (:foreground ,fg-dim :background ,bg-light))))
    `(magit-blame-date ((t (:foreground ,fg-dim))))
    `(magit-blame-hash ((t (:foreground ,accent))))

    `(org-table ((t (:foreground ,fg))))
    `(org-code ((t (:foreground ,syntax-string))))
    `(org-verbatim ((t (:foreground ,syntax-string))))
    `(org-link ((t (:foreground ,syntax-keyword))))
    `(org-headline-done ((t (:foreground ,fg-darker :strike-through t))))
    `(org-done ((t (:foreground ,term-green :strike-through t))))
    `(org-todo ((t (:foreground ,term-yellow))))
    `(org-block ((t (:background ,bg-light :foreground ,fg))))
    `(org-block-begin-line ((t (:foreground ,fg-dim :background ,bg-lighter))))
    `(org-block-end-line ((t (:foreground ,fg-dim :background ,bg-lighter))))

    `(js2-function-call ((t (:foreground ,syntax-function))))
    `(js2-object-prop ((t (:foreground ,syntax-property))))
    `(js2-variable-name ((t (:foreground ,syntax-variable))))
    `(js2-error ((t (:foreground ,term-red))))

    `(yaml-key ((t (:foreground ,syntax-keyword))))
    `(yaml-value ((t (:foreground ,syntax-string))))

    `(flymake-error ((t (:foreground ,term-red :underline t))))
    `(flymake-warning ((t (:foreground ,term-yellow :underline t))))
    `(flymake-info ((t (:foreground ,accent :underline t))))

    `(flycheck-error ((t (:foreground ,term-red))))
    `(flycheck-warning ((t (:foreground ,term-yellow))))
    `(flycheck-info ((t (:foreground ,accent))))
    `(flycheck-fringe-error ((t (:foreground ,term-red))))
    `(flycheck-fringe-warning ((t (:foreground ,term-yellow))))
    `(flycheck-fringe-info ((t (:foreground ,accent))))

    `(term-color-0 ((t (:background ,term-black :foreground ,term-black))))
    `(term-color-1 ((t (:background ,term-red :foreground ,term-red))))
    `(term-color-2 ((t (:background ,term-green :foreground ,term-green))))
    `(term-color-3 ((t (:background ,term-yellow :foreground ,term-yellow))))
    `(term-color-4 ((t (:background ,term-blue :foreground ,term-blue))))
    `(term-color-5 ((t (:background ,term-magenta :foreground ,term-magenta))))
    `(term-color-6 ((t (:background ,term-cyan :foreground ,term-cyan))))
    `(term-color-7 ((t (:background ,term-white :foreground ,term-white))))
  )
)

(provide-theme 'warp-dark)
