format = """
[┌───────────────────────────────────────────────────────────────](fg:#00c2ff,bg:#111111)
[│](fg:#00c2ff,bg:#111111) [ $($directory $style)](fg:#ffffff,bg:#0a0a0a)[$read_only](fg:#b4fa72,bg:#0a0a0a) [ $git_branch ](fg:#808080,bg:#0a0a0a)[$git_status](fg:#00c2ff,bg:#0a0a0a)
[└─>$](fg:#00c2ff,bg:#111111) """

[character]
success_symbol = "[➜](fg:#b4fa72)"
error_symbol = "[✗](fg:#ff8272)"

[directory]
style = "fg:#ffffff bg:#0a0a0a"
home_symbol = "~"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " $(char0xe0a0) "
style = "fg:#00c2ff bg:#0a0a0a"
format = "on [$symbol$branch]($style)"

[git_status]
style = "fg:#00c2ff bg:#0a0a0a"
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = "⚠️"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "🤷"
modified = "📝"
staged = "++"
renamed = "👅"
deleted = "🗑"

[shell]
bash_hover = "Help"

[aws]
style = "fg:#fefdc2 bg:#0a0a0a"
symbol = "☁️  "

[crystal]
style = "fg:#ffffff bg:#0a0a0a"
symbol = "💠  "

[docker]
style = "fg:#a5d5fe bg:#0a0a0a"
symbol = "🐳  "

[dotnet]
style = "fg:#00c2ff bg:#0a0a0a"
symbol = ".NET "

[elixir]
style = "fg:#ff8ffd bg:#0a0a0a"
symbol = "💧  "

[elm]
style = "fg:#00c2ff bg:#0a0a0a"
symbol = "🌳  "

[envvar]
style = "fg:#fefdc2 bg:#0a0a0a"

[git_metrics]
style = "fg:#b4fa72 bg:#0a0a0a"

[golang]
style = "fg:#00c2ff bg:#0a0a0a"
symbol = "🐹  "

[helm]
style = "fg:#00c2ff bg:#0a0a0a"
symbol = "⎈  "

[hg]
style = "fg:#ff8272 bg:#0a0a0a"
symbol = "⎇  "

[java]
style = "fg:#ff8272 bg:#0a0a0a"
symbol = "☕  "

[julia]
style = "fg:#ff8ffd bg:#0a0a0a"
symbol = "ĵ  "

[kotlin]
style = "fg:#ff8ffd bg:#0a0a0a"
symbol = "🅺  "

[memory_usage]
style = "fg:#ff8272 bg:#0a0a0a"
symbol = " ram "

[nodejs]
style = "fg:#b4fa72 bg:#0a0a0a"
symbol = "⬢  "

[package]
style = "fg:#ff8ffd bg:#0a0a0a"
symbol = "📦  "

[python]
style = "fg:#fefdc2 bg:#0a0a0a"
symbol = "🐍  "

[ruby]
style = "fg:#ff8272 bg:#0a0a0a"
symbol = "💎  "

[rust]
style = "fg:#ff8272 bg:#0a0a0a"
symbol = "🦀  "

[scala]
style = "fg:#ff8272 bg:#0a0a0a"
symbol = "🦁  "

[swift]
style = "fg:#ff8272 bg:#0a0a0a"
symbol = "🦉  "

[terraform]
style = "fg:#808080 bg:#0a0a0a"
symbol = "🏴‍☠️  "

[time]
style = "fg:#808080 bg:#0a0a0a"
format = "at [$time]($style) "
disabled = false

[username]
style_root = "fg:#ff8272 bg:#0a0a0a"
style_user = "fg:#00c2ff bg:#0a0a0a"
format_user = "[ $user]($style) "

[vcsh]
format = 'repo: [$repo]($style) '
symbol = "⎇ "

[status]
style = "fg:#ffffff bg:#111111"
format = "[$symbol $common_reason]($style)"
symbol_error = "✗"
symbol_success = "✓"
disabled = false
